---
- name: Install system dependencies for node
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - ipset
    - iptables
    - bridge-utils
    - libcgroup-tools
    - lvm2*
    - conntrack-tools
