---
- name: Fetch all route53 DNS hosted zones list
  route53_facts:
    query: hosted_zone
  register: zones_facts

- name: Finding details of each hosted zone
  route53_facts:
    query: hosted_zone
    hosted_zone_id: "{{item.Id}}"
    hosted_zone_method: details
  with_items: "{{zones_facts.HostedZones}}"
  register: zone_details

- name: Setting the zone when associated VPC is matched
  set_fact:
    zone: "{{ item.HostedZone }}"
  when: "{{item.VPCs.0.VPCId | match(vpc_id)}}"
  with_items: "{{ zone_details.results }}"

- name: List all records from route53 DNS zone
  route53_facts:
    query: record_sets
    hosted_zone_id: "{{zone.Id}}"
  register: record_sets

- name: Delete all records from route53 DNS zone
  route53:
    command: delete
    record: "{{ item.Name }}"
    value: "{{ item.ResourceRecords.0.Value }}"
    type: "{{ item.Type }}"
    zone: "{{domain}}"
    vpc_id: "{{vpc_id}}"
    private_zone: yes
  when: "{{not item.Name | match(domain)}}"
  with_items:
    "{{record_sets.ResourceRecordSets}}"

- name: Remove route53 DNS zone
  route53_zone:
    zone: "{{domain}}"
    state: absent
    vpc_region: "{{vpc.region}}"
    vpc_id: "{{vpc_id}}"
