language: python

env:
- TOXENV=py34
- TOXENV=flake8
- AWS_ACCESS_KEY_ID=dummy
- AWS_SECRET_ACCESS_KEY=dummy
- REGION=dummy

install:
- sudo touch /etc/ld.so.preload
- pip install tox

script:
- tox -vv tests

after_success:
  - coverage combine
  - codecov

notifications:
  email: false

# Don't fail on trunk versions.
matrix:
  allow_failures:
    - env: TOX_ENV=py34

notifications:
  email: false
