memory: 1G
cpu: 20%
disk: 1G
services:
- command: |
    exec treadmill sproc restapi -p 8000 --title 'Treadmill_Query_API' \
      -m trace,state,endpoint --cors-origin='.*'
  name: state-api
  restart:
    limit: 5
    interval: 60
endpoints:
- name: http
  port: 8000
  type: infra
