---
- name: Install gcc to Build S6
  yum:
    name: gcc
    state: present

- name: S6 Installations
  unarchive:
    remote_src: True
    src: "{{item}}"
    dest: "{{base_dir}}"
    mode: 0744
  with_items:
    - https://github.com/skarnet/s6/archive/v2.4.0.0.tar.gz
    - https://github.com/skarnet/execline/archive/v2.2.0.0.tar.gz
    - https://github.com/skarnet/skalibs/archive/v2.4.0.2.tar.gz

- name: Create S6,execline and skalibs soft links
  shell: "ln -s {{base_dir}}/{{item.0}}-{{item.1}} {{base_dir}}/{{item.0}}
         creates={{base_dir}}/{{item.0}}"
  with_together:
    - [s6, execline, skalibs]
    - ['2.4.0.0','2.2.0.0','2.4.0.2']

- name: Make s6
  shell: "./configure && make && make install"
  args:
    chdir: "{{base_dir}}/{{item}}"
  with_items:
    - skalibs
    - execline
    - s6