---
- name: Add route53 DNS Zone
  route53_zone:
    zone: "{{freeipa.domain}}"
    state: present
    vpc_region: "{{vpc.region}}"
    vpc_id: "{{vpc_id}}"

- name: Add DNS A record for IPA server
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: A
    record: "{{freeipa.server_hostname}}.{{freeipa.domain}}."
    value: "{{instance_facts_freeipa_server.instances[0].private_ip_address}}"

- name: Add kerberos TXT DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: TXT
    record: "_kerberos.{{freeipa.domain}}."
    value: "\"{{freeipa.realm}}\""

- name: Add kerberos master tcp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_kerberos-master._tcp.{{freeipa.domain}}."
    value: "0 100 88 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add kerberos tcp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_kerberos._tcp.{{freeipa.domain}}."
    value: "0 100 88 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add kpasswd tcp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_kpasswd._tcp.{{freeipa.domain}}."
    value: "0 100 464 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add ldap tcp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_ldap._tcp.{{freeipa.domain}}."
    value: "0 100 389 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add kerberos master udp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_kerberos-master._udp.{{freeipa.domain}}."
    value: "0 100 88 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add kerberos udp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_kerberos._udp.{{freeipa.domain}}."
    value: "0 100 88 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add kpasswd udp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_kpasswd._udp.{{freeipa.domain}}."
    value: "0 100 464 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add ntp udp SRV record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_ntp._udp.{{freeipa.domain}}."
    value: "0 100 123 {{freeipa.server_hostname}}.{{freeipa.domain}}."

- name: Add IP CA DNS A record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: A
    record: "ipa-ca.{{freeipa.domain}}."
    value: "{{instance_facts_freeipa_server.instances[0].private_ip_address}}"

- name: Add VPC ldap tcp SRV DNS record
  route53:
    command: create
    zone: "{{freeipa.domain}}"
    private_zone: true
    vpc_id: "{{vpc_id}}"
    type: SRV
    record: "_ldap._tcp.{{vpc_id}}.{{freeipa.domain}}."
    value: "0 100 1389 {{freeipa.server_hostname}}.{{freeipa.domain}}."

