aws_key_name: ms_treadmill_dev
ami_id: ami-6d1c2007
vpc:
  name: Treadmill
  cidr: 172.23.0.0/16
  region: us-east-1
  sg_name: sg_common
  sg_description: sg_rules_for_allowing_ssh_from_controller
  subnet:
    name: Treadmill
    cidr: 172.23.1.0/24
    az: us-east-1a
master:
  name: Treadmill_Master
  exact_count: 3
node_server:
  name: Treadmill_Node_Server
  exact_count: 1