---
- hosts: controller
  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - "{{aws_config | default('config/aws.yml')}}"
        - "config/treadmill.yml"
    - meta: refresh_inventory
  roles:
    - {role: instance, _name: "{{node_server.name}}", _exact_count: "{{node_server.exact_count}}", _instance_type: "{{node_server.instance_type}}" }
    - {role: dynamic-inventory}

- hosts: ec2instances
  become: yes
  environment:
    AWS_ACCESS_KEY_ID: "{{hostvars.localhost.ansible_env.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "{{hostvars.localhost.ansible_env.AWS_SECRET_ACCESS_KEY}}"
  vars:
    vpc_id: "{{hostvars.localhost.vpc_id}}"
  vars_files:
    - "{{aws_config | default('config/aws.yml')}}"
    - "config/treadmill.yml"
  roles:
    - {role: node-server}

- hosts: ec2apinode
  become: yes
  environment:
    AWS_ACCESS_KEY_ID: "{{hostvars.localhost.ansible_env.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "{{hostvars.localhost.ansible_env.AWS_SECRET_ACCESS_KEY}}"
  roles:
    - {role: api-services}
